### ISSUE TITLE
`elf2uf2-rs -d -s` fails on Mac when UF2 size is >128 KiB

### ISSUE THREAD

**Issue by eterevsky** [JoNil/elf2uf2-rs#13]
I am playing around with Raspberry Pico and I noticed that once the size of the firmware UF2 passes 128 KiB in size, `elf2uf2-rs -d -s` can no longer connect to the device. However this only happens when elf2uf2-rs is run on Mac.

To reproduce:

1. Build [this example](https://github.com/eterevsky/pico/blob/main/pico-usb-console/examples/hello-log.rs) on Mac.

2. Upload it to Raspberry Pi Pico using `elf2uf2-rs -d -s -v` (I'm using Pimoroni Pico Lipo, but it shouldn't matter).

The firmware opens the USB console and prints some debug output to it. 

Result on a Windows machine (correct):

```
Found pico uf2 disk E:\
Detected FLASH binary
Mapped segment 0x10000100->0x100001a8 (0x10000100->0x100001a8)
Mapped segment 0x10000000->0x10000100 (0x10000000->0x10000100)
Mapped segment 0x100001a8->0x1000d3f4 (0x100001a8->0x1000d3f4)
Mapped segment 0x1000d400->0x1000feac (0x1000d400->0x1000feac)
Mapped segment 0x1000feac->0x100100e4 (0x20000000->0x20000238)
Transfering program to pico
Page 0 / 257 0x10000000
...
Page 256 / 257 0x10010000

Found pico serial on COM3
Hello (latency: 330 ms)
System clock frequency: 125 MHz
1
2
3
...
```

Result on a Mac with exactly the same ELF binary: 

```
Found pico uf2 disk /Volumes/RPI-RP2
Detected FLASH binary
Mapped segment 0x10000100->0x100001a8 (0x10000100->0x100001a8)
Mapped segment 0x10000000->0x10000100 (0x10000000->0x10000100)
Mapped segment 0x100001a8->0x1000d3f4 (0x100001a8->0x1000d3f4)
Mapped segment 0x1000d400->0x1000feac (0x1000d400->0x1000feac)
Mapped segment 0x1000feac->0x100100e4 (0x20000000->0x20000238)
Transfering program to pico
Page 0 / 257 0x10000000
...
Page 256 / 257 0x10010000

```

and `elf2uf2-rs` silently exits.

**Comment by eterevsky** [comment]
Turns out it's just a matter of timeout when waiting for the serial port to open. Currently the hard-coded timeout is 2s. When increased, the serial port is successfully opened. @JoNil, I can send you a PR that either increases the timeout to 10s, or turns it into a separate command-line option. What do you prefer?

**Comment by JoNil** [comment]
I have increased the timeout on master
