### ISSUE TITLE
elf2uf2-rs tries to enumerate devices even when converting

### ISSUE THREAD

**Issue by DarkKirb** [JoNil/elf2uf2-rs#15]
I am trying to use elf2uf2-rs in a build step in nix. Currently, this is not possible due to the following error:

```
Error: Error { kind: Io(NotFound), description: "No such file or directory" }
```

strace says that /sys/subsystem, /sys/bus and /sys/class, all of which are missing, have been opened right before this error message is written

**Comment by JoNil** [comment]
You should probably fork this tool and only use the conversion part
