### ISSUE TITLE
Fails to program large disjoint image?

### ISSUE THREAD

**Issue by thejpster** [JoNil/elf2uf2-rs#23]
I tried to flash https://github.com/Neotron-Compute/Neotron-Pico-BIOS and it failed - I got a hardfault jumping from the BIOS to the OS, indicating the OS was not flashed correctly. 

I flashed the same ELF with the official elf2uf2 tool and it worked fine.

I suspect it may be because of the large gap between the end of one part of my binary and the start of the next.

**Comment by addap** [comment]
In case it's still relevant, the UF2 bootloader of the pico has a bug which breaks writing of UF2 files with partial sectors (https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf#errata-e14).
You can use #22 which implements filling up partial sectors with zero pages.

**Comment by JoNil** [comment]
Solved by #22?
