### ISSUE TITLE
Typo in the help message derived from comment by clap

### ISSUE THREAD

**Issue by Crest** [JoNil/elf2uf2-rs#8]
This [comment](https://github.com/JoNil/elf2uf2-rs/blob/91ae98873ed01971ab1543b98266a5ad2ec09210/src/main.rs#L39) contains a typo (deply instead of deploy) that's user visible because the comment is used by [clap](https://docs.rs/clap/latest/clap) e.g. in `elf2uf2-rs --help`'s output:
```
% elf2uf2-rs --help
elf2uf2-rs
Jonathan Nilsson

USAGE:
    elf2uf2-rs [OPTIONS] <INPUT> [OUTPUT]

ARGS:
    <INPUT>     Input file
    <OUTPUT>    Output file

OPTIONS:
    -d, --deploy     Deploy to any connected pico
    -h, --help       Print help information
    -s, --serial     Connect to serial after deply
    -v, --verbose    Verbose
```

**Comment by JoNil** [comment]
Fixed!
